### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#12]
Anschließend wird unseres Projekt mit der Bezeichnung 1.0 veröffentlicht

**Comment by nicolaiparlog** [comment]
Hier ein paar Details wie genau man ein Release macht (wenn ihr alle anderen [Issues zur Projektinfrastruktur](https://github.com/DenisBrendel/Informatik-Projekt/milestone/1) erledigt habt):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen

Den letzten Schritt hab ich schon lange nicht mehr gemacht, kann sein, dass ihr da ein wenig suchen müsst.

**Comment by DenisBrendel** [comment]
Alles Klar! Vielen Dank für die Hilfestellung, werden wir schnon hinkriegen!!
 

Gesendet: Donnerstag, 03. August 2017 um 22:43 Uhr
Von: "Nicolai Parlog" <notifications@github.com>
An: DenisBrendel/Informatik-Projekt <Informatik-Projekt@noreply.github.com>
Cc: "Denis Brendel" <denis-brendel@web.de>, Author <author@noreply.github.com>
Betreff: Re: [DenisBrendel/Informatik-Projekt] Release version 1.0 (#12)


Hier ein paar Details wie genau man ein Release macht (wenn ihr alle anderen Issues zur Projektinfrastruktur erledigt habt):


	master auschecken
	mit mvn clean install und java-jar target/...jar sicherstellen, dass alles funktioniert
	in der pom.xml bei der Version -SNAPSHOT entfernen
	nochmal mvn clean install und die JAR aus dem target-Ordner (beachte, dass -SNAPSHOT fehlt) irgendwohin kopieren
	neuen Commit auf master mit der Message "Release version 1.0" (oder so)
	den Commit taggen
	in der pom.xml die Version 2.0-SNAPSHOT eintragen
	neuen Commit auf master mit der Message "Start work on 2.0" (oder so)
	alles pushen (mit tags)
	auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen


Den letzten Schritt hab ich schon lange nicht mehr gemacht, kann sein, dass ihr da ein wenig suchen müsst.

**Comment by DenisBrendel** [comment]
bzgl. Tags schlage ich vor die lightweight Version zu benutzen, da wir ein einfaches Projekt haben.

**Comment by nicolaiparlog** [comment]
Ja, lightweight Tags sind ausreichend.
