### ISSUE TITLE
Erstelle Klassen für main, Autos, Straße

### ISSUE THREAD

**Issue by FrEeDoM-Sc2** [DenisBrendel/Informatik-Projekt#20]

**Comment by DenisBrendel** [comment]
Als Anfang schlage ich vor, dass wir das Konzept vom Programm bestimmen, indem wir die Struktur des Projekts entwickeln.
Zum Bspl. :

- values
- entities
- accounts
- methods
- Misc

**Comment by DenisBrendel** [comment]
Mein Vorschlag wäre:

- requirements 

  - car:          anounce if it wants to drive or not
  - network:  has own capacity
  - network:  calculate the trafic
  - network:  decide if all cars will drive or not

- values
  -capacity
- entities
  -car
  -roadnetwork
- methods
  -calculate
  -decide
- Misc
  -single step that meant 1 hour

**Comment by FrEeDoM-Sc2** [comment]
Das muss ich mir auf dem Video vom Parlog noch mal anschauen...


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Denis Brendel <notifications@github.com> 
Datum: 05.08.17  15:46  (GMT+01:00) 
An: DenisBrendel/Informatik-Projekt <Informatik-Projekt@noreply.github.com> 
Cc: FrEeDoM-Sc2 <m.maison.sc2@gmx.de>, Author <author@noreply.github.com> 
Betreff: Re: [DenisBrendel/Informatik-Projekt] Erstelle Klassen für main, Autos, Straße (#20) 

Mein Vorschlag wäre:


requirements

car:          anounce if it wants to drive or not
network:  has own capacity
network:  calculate the trafic
network:  decide if all cars will drive or not



values

-capacity


entities

-car

-roadnetwork


methods

-calculate

-decide


Misc

-single step that meant 1 hour



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DenisBrendel/Informatik-Projekt","title":"DenisBrendel/Informatik-Projekt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DenisBrendel/Informatik-Projekt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DenisBrendel in #20: Mein Vorschlag wäre:\r\n\r\n- requirements \r\n\r\n  - car:          anounce if it wants to drive or not\r\n  - network:  has own capacity\r\n  - network:  calculate the trafic\r\n  - network:  decide if all cars will drive or not\r\n\r\n- values\r\n  -capacity\r\n- entities\r\n  -car\r\n  -roadnetwork\r\n- methods\r\n  -calculate\r\n  -decide\r\n- Misc\r\n  -single step that meant 1 hour"}],"action":{"name":"View Issue","url":"https://github.com/DenisBrendel/Informatik-Projekt/issues/20#issuecomment-320444604"}}}

**Comment by DenisBrendel** [comment]
Ja das meinte ich mit"wants to drive or not" also false or true
