### ISSUE TITLE
Tests schreiben

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#26]

**Comment by DenisBrendel** [comment]
@nicolaiparlog wie soll man random fun testen O_O ? oder Sezt man für diese variable den wert den wir prüfen wollen?

**Comment by nicolaiparlog** [comment]
Ja, das ist nicht ganz einfach. Ich glaube nicht, dass wir das bis zur Deadline noch hinbekommen.

**Comment by DenisBrendel** [comment]
Sinds ja noch 7 Stunden :D

**Comment by nicolaiparlog** [comment]
Wie in der Mail geschrieben: Die Sachen, die da sind müssen funktionieren. Wenn das Programm nicht ordentlich gebaut und ausgeführt werden kann, ist das Ergebnis wesentlich schlechter, als wenn ein Issue fehlt.

**Comment by DenisBrendel** [comment]
Ich bin mit Test fast fertig, nur wo random geprüft wird hänge ich , gibts vlt nen trick? @nicolaiparlog

**Comment by DenisBrendel** [comment]
Muss iwe der variable `randomValue` selbst den wert zuweisen...

**Comment by DenisBrendel** [comment]
ich kann höchstens die funktion genauso in tests schreiben aber das ist auch nicht richtig...

**Comment by DenisBrendel** [comment]
und wie man delay fun testet habe ich auch keine idee es muss iwie geprüft werden ob er das richtige `if` gewählt hat, aber wie...

**Comment by nicolaiparlog** [comment]
Zufällige Abläufe zu testen ist schwierig - ist ok, wenn eure Tests das nicht abdecken.

**Comment by DenisBrendel** [comment]
Übrigens, habe bei den Tests festgestellt, dass Funktion percent nicht ganz  richtig funktioniet hat, habe aber das beseitigt ( musstte nur einmal gerundet werden)
