### ISSUE TITLE
Simulation für den ganzen Tag

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#31]
@nicolaiparlog Wenn ich richtig verstanden habe,  jedes Auto soll jetzt wissen zu welchen Stunden (`Steps`) war es verzögert (also hat in unserem Fall `Car.delay=true` bekommen) und zu welchen könnte es Fahren (`Car.delay =false`) aber das auto will bei jedem `Step` Fahren (in unserem Fall `car.driveOrNot = true` und zwar immer sozusagen) Die Entscheidung für Verzögerung basiert auf der `capacity` und der Wahrscheinlichkeit

**Comment by DenisBrendel** [comment]
@nicolaiparlog Wenn ich richtig verstanden habe,  jedes Auto soll jetzt wissen zu welchen Stunden (`Steps`) war es verzögert (also hat in unserem Fall `Car.delay=true` bekommen) und zu welchen könnte es Fahren (`Car.delay =false`) aber das auto will bei jedem `Step` Fahren (in unserem Fall `car.driveOrNot = true` und zwar immer sozusagen) Die Entscheidung für Verzögerung basiert auf der `capacity` und der Wahrscheinlichkeit

**Comment by DenisBrendel** [comment]
Oder ist es so, dass sobald das Auto für einen `step` verzögert wurde, wird der Wunsch für nächsten `step` rückgesetzt und erst dann wird das Auto versuchen noch mal zu fahren. Aber für das ganze muss normalerweise der allererste Wunsch `true` sein?

**Comment by nicolaiparlog** [comment]
Zunächst mal muss das Auto für jeden der 24 Simulationsschritte wissen, ob es da fahren will oder nicht. Das kann auf verschiedene Art und Weisen angeben, eine Möglichkeit wäre eine `List<Int>`, die die Stunden enthält an denen das Auto fahren will.

Dann soll festgehalten werden, zu welchen Stunden das Auto gestanden hat (weil es nicht fahren wollte), gefahren ist oder im Stau gestanden hat. Das könnte man mit zwei `Int`-Listen machen - eine für gefahren, eine für gestaut.

Es ist vernünftig, das Aktualisieren dieser Listen in `Car` zu machen, nicht in `RoadNetwork`. D.h. `RoadNetwork` sollte z.B. eine `Car`-Methode `drive(hour: Int)` aufrufen, die sich dann merkt, dass gefahren wurde.

Wenn du das angehst, achte darauf, nicht versehentlich auch #32 oder #33 zu lösen. Es ist vollkommen ok, wenn das CSV Lesen/Schreiben noch nicht das richtige macht. Der Code muss kompilieren, aber der CSV-Teil darf ruhig komische Sachen machen (z.B. keinen Fahrwunsch mehr laden oder keine Verspätungen schreiben) - lösen kannst du das in #32/#33.

Wenn dir das mit der Verzögerung (wenn das Auto in Stunde `x` nicht fahren konnte, will es in `x+1` fahren) noch unklar ist, lass es erstmal weg und mach dafür ein eigenes Issue auf.

**Comment by DenisBrendel** [comment]
Achso, jetzt habe ich kapiert das Auto versucht auf die Anzahl der gewünschten stunden zu kommen

**Comment by nicolaiparlog** [comment]
Vor allen Dingen versucht es in den entsprechenden Stunden zu fahren.

**Comment by DenisBrendel** [comment]
@nicolaiparlog Noch mal zum verständniss das Auto will zB in 1 2 3 4 fahren, wurde aber verzögert(durch zufall) in 2 und 3, das Auto fährt dann in 1  4 5 6 oder? und noch mal soll das auto verzögert werden auch wenn es nicht fahren will?

**Comment by nicolaiparlog** [comment]
Die Verzögerung, die du beschreibst ist korrekt. Ich habe festgestellt, dass manche Teams für dieses Detail relativ lange gebraucht haben. Ich schlage vor, dass du für den Aspekt ein neuen Issue aufmachst und dann dieses hier erstmal ohne dieses Feature lost.

**Comment by DenisBrendel** [comment]
Ja..dann macht es echt einfacher..:D
