### ISSUE TITLE
README.md Datei erstellen und vervollständigen

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#4]
In README.md Datei soll enthalten sein:
-Unsere Namen  (@FrEeDoM-Sc2 /@DenisBrendel)
-Name des Mentors (@nicolaiparlog)
-Beschreibung des Projekts
-Kurze Beschreibung der Liezens Datei
-Anforderungen und Ziele des Projekts

**Comment by nicolaiparlog** [comment]
Die Lizenz soll als eigene Datei `LICENSE.txt` ins Repository und in der README nur erwähnt und verlinkt werden.

**Comment by nicolaiparlog** [comment]
Der Code of Conduct sollte ebenfalls erwähnt und verlinkt werden.
