### ISSUE TITLE
Simulation für 24 Stunden mit next step erweiterung

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#44]
Wie gesagt hab mehreres versucht, bis ich `contain` Methode für sich kennengelernt habe, die Sache war dann auch leichter aber trotzdem noch nicht ganz...
Ich vermute es muss ein Merker gesetzt werden, und dann in `drive` Methode gefragt "du wahrst fahren"(`drivenAt.contains(step)` und warst verzögert dann setze den Merker "Will fahren im nächsten Schritt" 
aber dann auch verglichen ob das Auto schon fahren war  (so ist mir schon mal passiert, in der Ausgabe `drivenAt` waren doppelte Stunden, aber nächste Stunde hat er ja gesetzt :laughing: )

**Comment by DenisBrendel** [comment]
Merke gerade das muss iwie wie counter sein, wenn zb das Auto in 1 2 3 4 15 fahren will und wurde auch in 1 2 3 4 **8** verzögert muss es in 5 6 7 9 10 fahren

**Comment by nicolaiparlog** [comment]
Genau.
