### ISSUE TITLE
Integration mit Travis 

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#9]
Hier Müssen wir uns an Nicolai Parlog wenden

**Comment by nicolaiparlog** [comment]
Ok... Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @DenisBrendel.

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich bereite solange schonmal die `.travis.yml` vor.

**Comment by DenisBrendel** [comment]
Sollte von mir eigentlich erledigt sein, da ich aber das nie gemacht habe bin ich mir nicht sicher ob alles korrekt ist
